apiVersion: v1
kind: Service
metadata:
  name: core-k8s-service
  namespace: voucher-management-app
spec:
  selector:
    app: voucher-app-core
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
