apiVersion: apps/v1
kind: Deployment
metadata:
  name: voucher-app-core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voucher-app-core
  template:
    metadata:
      labels:
        app: voucher-app-core
    spec:
      containers:
        - name: voucher-app-core
          image: public.ecr.aws/s6y5a7e8/voucher-app-core:v15
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: db_password
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aws_s3_access_key_id
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aws_s3_secret_key_id
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: AES_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aes_secret
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: jwt_public_key
            - name: AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: AUTH_URL
            - name: AUDIT_SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: AUDIT_SQS_URL
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: FRONTEND_URL
          resources:
           requests:
             cpu: "50m"
             memory: "250Mi"
           limits:
             cpu: "350m"
             memory: "500Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: core-k8s-service
spec:
  selector:
    app: voucher-app-core
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
